# Generated by Django 4.2.5 on 2023-10-14 09:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="profile",
            table="profiles_table",
        ),
        migrations.AlterModelTable(
            name="topic",
            table="topics_table",
        ),
    ]
